//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: CardTransformationService.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `CardTransformationClient`, then call methods of this protocol to make API calls.
internal protocol CardTransformationClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: CardTransformationClientInterceptorFactoryProtocol? { get }

  func getCardTransformationData(
    _ request: GetCardTransformationDataRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<GetCardTransformationDataRequest, GetCardTransformationDataResponse>
}

extension CardTransformationClientProtocol {
  internal var serviceName: String {
    return "CardTransformation"
  }

  /// Unary call to GetCardTransformationData
  ///
  /// - Parameters:
  ///   - request: Request to send to GetCardTransformationData.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getCardTransformationData(
    _ request: GetCardTransformationDataRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<GetCardTransformationDataRequest, GetCardTransformationDataResponse> {
    return self.makeUnaryCall(
      path: CardTransformationClientMetadata.Methods.getCardTransformationData.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCardTransformationDataInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension CardTransformationClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "CardTransformationNIOClient")
internal final class CardTransformationClient: CardTransformationClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: CardTransformationClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: CardTransformationClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the CardTransformation service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: CardTransformationClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct CardTransformationNIOClient: CardTransformationClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: CardTransformationClientInterceptorFactoryProtocol?

  /// Creates a client for the CardTransformation service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: CardTransformationClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol CardTransformationAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: CardTransformationClientInterceptorFactoryProtocol? { get }

  func makeGetCardTransformationDataCall(
    _ request: GetCardTransformationDataRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<GetCardTransformationDataRequest, GetCardTransformationDataResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension CardTransformationAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return CardTransformationClientMetadata.serviceDescriptor
  }

  internal var interceptors: CardTransformationClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetCardTransformationDataCall(
    _ request: GetCardTransformationDataRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<GetCardTransformationDataRequest, GetCardTransformationDataResponse> {
    return self.makeAsyncUnaryCall(
      path: CardTransformationClientMetadata.Methods.getCardTransformationData.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCardTransformationDataInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension CardTransformationAsyncClientProtocol {
  internal func getCardTransformationData(
    _ request: GetCardTransformationDataRequest,
    callOptions: CallOptions? = nil
  ) async throws -> GetCardTransformationDataResponse {
    return try await self.performAsyncUnaryCall(
      path: CardTransformationClientMetadata.Methods.getCardTransformationData.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCardTransformationDataInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct CardTransformationAsyncClient: CardTransformationAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: CardTransformationClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: CardTransformationClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol CardTransformationClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'getCardTransformationData'.
  func makeGetCardTransformationDataInterceptors() -> [ClientInterceptor<GetCardTransformationDataRequest, GetCardTransformationDataResponse>]
}

internal enum CardTransformationClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "CardTransformation",
    fullName: "CardTransformation",
    methods: [
      CardTransformationClientMetadata.Methods.getCardTransformationData,
    ]
  )

  internal enum Methods {
    internal static let getCardTransformationData = GRPCMethodDescriptor(
      name: "GetCardTransformationData",
      path: "/CardTransformation/GetCardTransformationData",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol CardTransformationProvider: CallHandlerProvider {
  var interceptors: CardTransformationServerInterceptorFactoryProtocol? { get }

  func getCardTransformationData(request: GetCardTransformationDataRequest, context: StatusOnlyCallContext) -> EventLoopFuture<GetCardTransformationDataResponse>
}

extension CardTransformationProvider {
  internal var serviceName: Substring {
    return CardTransformationServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetCardTransformationData":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<GetCardTransformationDataRequest>(),
        responseSerializer: ProtobufSerializer<GetCardTransformationDataResponse>(),
        interceptors: self.interceptors?.makeGetCardTransformationDataInterceptors() ?? [],
        userFunction: self.getCardTransformationData(request:context:)
      )

    default:
      return nil
    }
  }
}

#if compiler(>=5.6)

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol CardTransformationAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: CardTransformationServerInterceptorFactoryProtocol? { get }

  @Sendable func getCardTransformationData(
    request: GetCardTransformationDataRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> GetCardTransformationDataResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension CardTransformationAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return CardTransformationServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return CardTransformationServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: CardTransformationServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetCardTransformationData":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<GetCardTransformationDataRequest>(),
        responseSerializer: ProtobufSerializer<GetCardTransformationDataResponse>(),
        interceptors: self.interceptors?.makeGetCardTransformationDataInterceptors() ?? [],
        wrapping: self.getCardTransformationData(request:context:)
      )

    default:
      return nil
    }
  }
}

#endif // compiler(>=5.6)

internal protocol CardTransformationServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'getCardTransformationData'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetCardTransformationDataInterceptors() -> [ServerInterceptor<GetCardTransformationDataRequest, GetCardTransformationDataResponse>]
}

internal enum CardTransformationServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "CardTransformation",
    fullName: "CardTransformation",
    methods: [
      CardTransformationServerMetadata.Methods.getCardTransformationData,
    ]
  )

  internal enum Methods {
    internal static let getCardTransformationData = GRPCMethodDescriptor(
      name: "GetCardTransformationData",
      path: "/CardTransformation/GetCardTransformationData",
      type: GRPCCallType.unary
    )
  }
}
